### ISSUE TITLE
ست کردن زمان به همراه تاریخ به عنوان مقدار اولیه

### ISSUE THREAD

**Issue by rahkarpouya** [babakhani/PersianDate#100]
با سلام
چگونه می شود زمان و تاریخ رو با هم به عنوان مقدار اولیه ست کرد؟ با هر فرمتی که گزاشتیم نشد و فقط تاریخ رو میگیره اون هم با فرمت زیر

1399-07-13

**Comment by mort3za** [comment]
Pass a Unix timestamp instead.  
https://codepen.io/mort3za/pen/oNLvvPw
