### ISSUE TITLE
 سلام

### ISSUE THREAD

**Issue by mohammmad13821388** [babakhani/PersianDate#115]
Hi

**Comment by mohammmad13821388** [comment]
سلام

**Comment by mohammmad13821388** [comment]
سلام و خدا قوت
ببخشید من وقتی میخوام روی بک گراند سایتم عکس بزارم انگار آدرس عکسمو نمیخونه همش سفید میاد 
 <img src=" ادرس عکس میزارم نمیاره" alt=" " title=" " >
با تشکر

**Comment by mort3za** [comment]
سلام. سوال شما به این ریپازیتوری ارتباطی نداره.
