### ISSUE TITLE
wrong date client

### ISSUE THREAD

**Issue by nassajis** [babakhani/PersianDate#15]
سلام
یه سوال 
اگه تاریخ سیستم کاربرغلط باشه تاریخ ها کامل غلط میشین
برای تصحیح این کار چیکار باید کرد؟

**Comment by babakhani** [comment]
درود
می تونید تاریخ رو از سمت سرور ارسال کنید و از اون استفاده کنید.

**Comment by nassajis** [comment]
اوکی درست میگید باید از سرور ست شه ولی چطوری به ورودیش کنم به سیستم شما؟
یعنی تایم استمپ بدم ؟ چی بدم ؟ چطوری باید این کار رو بکنم؟
من تاریخ از سمت سرور میگیرم میلادی و تایم استمپشو دارم ولی نمیدونم چطوری باید به سیستم تاریخ شما ورودی بدم

**Comment by babakhani** [comment]
http://babakhani.github.io/PersianWebToolkit/doc/persiandate/0.1.8
 توضیحات کامل در بخش:
parsing
آورده شده است.
در صورتی نیاز به راهنمایی بیشتر نمونه ای روی اینجا:
jsfiddle.net
بسازید و لینک آن را در همین صفحه ارسال نمایید.
سپاس
