### ISSUE TITLE
گزارش خطا - mindate

### ISSUE THREAD

**Issue by svfnix** [babakhani/PersianDate#17]
با سلام و عرض تشکر و خسته نباشید
در بخشی از کد ها با خطایی مواجه شدم که خواستم گزارش بدم
زمانی که مقدار mindate تعیین میشه ماهی که در اون هستید از لیست ماه ها قابل انتخاب نیست
فرضا ما مقدار mindate رو برابر با ۱۵ شهریور میزاریم و از طریق نوارابزار به لیست ماه ها میریم ماه شهریور قابل انتخاب نیست
من با تغییر بخشی از کد شما مشکل رو رفع کردم

_checkMonthAccess: function (month) {
        if (this.datepicker.state._filetredDate) {
            var y = this.datepicker.state.view.year;
            var monthUnix = new pDate([y, month]).unix() \* 1000;
            if (monthUnix >= this.datepicker.state.filterDate.start.unixDate &&
                monthUnix <= this.datepicker.state.filterDate.end.unixDate
                ) {
                return true;
            } else {
                return false;
            }
        }
        else {
            return this.datepicker.checkMonth(month);
        }
    },

تبدیل شد به

_checkMonthAccess: function (month) {
        if (this.datepicker.state._filetredDate) {

```
        var y = this.datepicker.state.view.year;
        var min_y = this.datepicker.state.filterDate.start.year;
        var min_m = this.datepicker.state.filterDate.start.month;
        var max_y = this.datepicker.state.filterDate.end.year;
        var max_m = this.datepicker.state.filterDate.end.month;

        if ((min_y > y) || ((min_y == y) && (min_m > month)) || (max_y < y) || ((max_y == y) && (max_m < month)))
        {
            return false;
        }
        else
        {
            return true;        
        }        
    }
    else {
        return this.datepicker.checkMonth(month);
    }
},
```

**Comment by svfnix** [comment]
ادامه این مشکل در بخش renderday‌s مشاهده شد که از طریق کد زیر رفع شد

if (self.datepicker.state._filetredDate) {
                        if (self.minDate && self.maxDate) {
                            if (thisUnix >= self.minDate && thisUnix <= self.maxDate) {
                                $(this).addClass(self.cssClass.disbaled);
                            } else {
                                $(this).removeClass(self.cssClass.disbaled);
                            }
                        } else if (self.minDate) {
                            if (thisUnix >= self.minDate) {
                                $(this).addClass(self.cssClass.disbaled);
                            }
                        } else if (self.maxDate) {
                            if (thisUnix <= self.maxDate) {
                                $(this).removeClass(self.cssClass.disbaled);
                            }
                        }
                    } else {
                        if (self.datepicker.checkDate(thisUnix)) {
                            $(this).removeClass(self.cssClass.disbaled);
                        } else {
                            $(this).addClass(self.cssClass.disbaled);
                        }
                    }

تبدیل شد به 

if (self.datepicker.state._filetredDate) {
                        if (self.minDate && self.maxDate) {
                            if (thisUnix >= self.minDate && thisUnix <= self.maxDate) {
                                $(this).removeClass(self.cssClass.disbaled);
                            } else {
                                $(this).addClass(self.cssClass.disbaled);
                            }
                        } else if (self.minDate) {                        	
                            if (thisUnix >= self.minDate) {
                                $(this).removeClass(self.cssClass.disbaled);
                            }
                        } else if (self.maxDate) {alert(thisUnix +":"+ self.minDate);
                            if (thisUnix <= self.maxDate) {
                                $(this).addClass(self.cssClass.disbaled);
                            }
                        }
                    } else {
                        if (self.datepicker.checkDate(thisUnix)) {
                            $(this).removeClass(self.cssClass.disbaled);
                        } else {
                            $(this).addClass(self.cssClass.disbaled);
                        }
                    }

**Comment by babakhani** [comment]
با سپاس ازشما
اگر مایلید اصلاحات شما زودتر در پروژه اعمال شود لطفا لینک زیر را بررسی کنید و از طریق معرفی شده روی پروژه کار کنید 
https://guides.github.com/activities/contributing-to-open-source/
