### ISSUE TITLE
Wrong IsLeapYear result?

### ISSUE THREAD

**Issue by Mds92** [babakhani/PersianDate#18]
I've tested the library,
`isLeapYear` returns `false` for 1403 whiles 1403 is a leap year !!!

<pre>persianDate([1403,1,1]).isLeapYear()</pre>

Also, it returns `true` for 1404, whiles 1404 is not a leap year !!!

What's wrong with it?

**Comment by babakhani** [comment]
درود
بر مبنای الگوریتم استفاده شده در سایت : http://eclipse.gsfc.nasa.gov/SKYCAL/algorithm.js
 1403 سال کبیسه نیست. من با بخش تقویم موسسه ژیوفیزیک دانشگاه تهران تماس گرفتم. و طبق گفته کارشناسان محترم این موسسه دو حالت برای محاسبه سال کبیسه وجود داره که یکی بر اساس "قاعده نوروز تحویلی" است که بر اساس مشاهدات نجومی انجام می شه و الگوریتم مشخصی ندارد. و دیگری بر اساس دوره های 2820 و یا 33 ساله می باشد. که این دوره ها در سال هایی با هم اختلاف دارند. اینکه کدام یک از دوره ها مبنای محاسبه قرار بگیرد بستگی به قانون رسمی محاسبات تقویمی کشور دارد. هنوز هیچ یک از این دوره ها به صورت قانون رسمی به تصویب نرسیده. و طبق اطلاعات به دست آمده چنین قانونی در دست طرح و تصویب در مجلس است و تا قبل از تصویب هر یک از این دوره ها ما به طور یقین نمی توانیم سال کبیسه را در برخی سالها که نزدیک ترین آن 1403 است محاسبه کنیم.
به همین دلیل در حال حاضر ما مبنای محاسبات خود را با استناد به اگوریتم استفاده شده در سایت ناسا دوره های 2820 ساله قرار داده ایم.
با سپاس فراوان از گزارش شما.
شاد باشید.

**Comment by babakhani** [comment]
also you can read 
http://www.astro.uni.torun.pl/~kb/Papers/EMP/PersianC-EMP.htm
http://www.fourmilab.ch/documents/calendar/
