### ISSUE TITLE
fixPosition : جهت نمایش صحیح بروز رسانی کنید 

### ISSUE THREAD

**Issue by sarayousefi** [babakhani/PersianDate#21]
fixPosition: function (self) {
                if (!self._inlineView) {
                    var inputX = self.inputElem.offset().top;
                    var inputY = self.inputElem.offset().left;
                    var mainHeight = self.fullHeight(self.element.main);
                    if (self.position === "auto") {
                        var inputHeight = self.fullHeight(self.inputElem);
                        if(inputX - $(window).scrollTop() > mainHeight){
                            self.element.main.css({
                                top: (inputX - mainHeight) + 'px',
                                left: inputY + 'px'
                            });
                        }else{
                            self.element.main.css({
                                top: (inputX + inputHeight) + 'px',
                                left: inputY + 'px'
                            });
                        }
                    } else {
                        self.element.main.css({
                            top: (inputX + self.position[0]) + 'px',
                            left: (inputY + self.position[1]) + 'px'
                        });
                    }
                }
                return this;
            }

**Comment by babakhani** [comment]
must move to [persian datepicker](https://github.com/babakhani/PersianDate/issues)
