### ISSUE TITLE
اضافه کردن تگ های اچ تی ام ال به ازای هر بار نیو کردن

### ISSUE THREAD

**Issue by masoodinfo** [babakhani/PersianDate#24]
سلام
ممنون از کامپوننت خوبتون!
برادر دیت پیکر خارجی هر چند بار هم که ازش نیو کنی با تگ های اچ تی ام ال اضافه شده در بار اول کار می کنه!
ولی این کامپوننت به ازای هر بار که یک شی ازش میسازی ،کد اچ تی ام ال  رو به صفحه اضافه می کنه!
![pdate](https://cloud.githubusercontent.com/assets/10396734/20254772/a1dfe38e-aa4c-11e6-9ab2-5a8c3f7330bd.png)

واین در جاهایی که به صورت داینامیک میخوام ازش استفاده کنم مشکل ساز میشه
```javascript

dataInit: function (elem)
                {
                    
                    var myval = elem.value;
                    $(elem).pDatepicker(
                    {
                        format: 'YYYY/MM/DD',
                        autoClose: true
                    }
                    );
                    if (myval != "") {
                        var datearray = myval.split('/').map(function (item) {
                            return parseInt(item, 10);
                        });
                        $(elem).pDatepicker('setDate', datearray);
                    }

                   
                }
```
اگر من استفاده ناصحیح  می کنم بفرمایید

**Comment by pylover** [comment]
Good point

**Comment by babakhani** [comment]
This issue must move to [pwt.datepicker ](https://github.com/babakhani/PersianDate/issues)
