### ISSUE TITLE
عدم نمایش صحیح تاریخ برگشتی از سرور

### ISSUE THREAD

**Issue by farhood-sh** [babakhani/PersianDate#25]
> سلام 
>  وقتی که مقدار رشته تاریخ شمسی برگشتی از سرور در
>  MVC
>  به فیلد مورد نظر
>  Bind
>  میشه مقدار آن عوض میشه
> مثلا مقدار برگشتی از سرور ۱۳۹۵/۰۸/۰۸ هست ولی در دیت پیکر ۷۷۴/۰۵/۱۷ نمایش داده میشه

```
<input asp-for="FromDate" class="persian-datepicker" type="text">

<script>
$('.persian-datepicker').persianDatepicker({
        format: 'YYYY/MM/DD',
        observer: true
    });
</script>
```

**Comment by babakhani** [comment]
this is about persian-datepicker and this project is part of it.
any way you can't set input value by this format. you must set as gregorian date.
