### ISSUE TITLE
مشکل با 2 فروردین 1396

### ISSUE THREAD

**Issue by AhmadValipour** [babakhani/PersianDate#27]
وقتی سال و ماه و روز 2 فروردین 1396 رو به عنوان پارامتر میفرستین ، تاریخ 1 فروردین رو برمیگیردونه

**Comment by miladamirzadeh** [comment]
تو سایت های مختلفی این مشکل دیده میشه ما هم دقیقا تو یه پروژه بزرگ و مشابه به این  مشکل برخوردیم

**Comment by babakhani** [comment]
Please check last 0.2.0 version  and if problem still exist open this issue.
