### ISSUE TITLE
استفاده به صورت import

### ISSUE THREAD

**Issue by hossein-nasr** [babakhani/PersianDate#28]
سلام
من می‌خوام که از فایل ها به 
`import` persianDate form 'persian-date'`;
استفاده کنم. چطور میتونم این کار رو بکنم؟
به نظر شبیه به سایر کتابخانه ها نیست.

**Comment by babakhani** [comment]
Currently ES6 features doesn't support.

**Comment by hoossseinut** [comment]
is it possible to use it this library with es5? I mean 
```
var persianDate = require('persian-date');
```
