### ISSUE TITLE
problem with safari

### ISSUE THREAD

**Issue by Palvaneh** [babakhani/PersianDate#31]
everything looks good in chrome but in safari something goes wrong!
`NaN/NaN/NaN ساعت NaN:NaN`

any ideas would be greatly appreciated

**Comment by babakhani** [comment]
Which version do you use?

**Comment by mohammadamd** [comment]
The pattern yyyy-MM-dd isn't an officially supported format for Date constructor. Firefox and Chrome seems to support it, but don't count on other browsers doing the same.

Here are some of supported strings:

MM-dd-yyyy
yyyy/MM/dd
MM/dd/yyyy
MMMM dd, yyyy
MMM dd, yyyy

you have to replace - with / to fix you problem (in date that you pass to persianDate)
