### ISSUE TITLE
Incorrect time conversion

### ISSUE THREAD

**Issue by Ardeshir81** [babakhani/PersianDate#32]
HI!
I tested a particular timestamp using minified persianDate version 0.1.8;

timestamp is : 1498208777214

I did this  : persianDate(1498208777214).toArray()
and the result was this array : [1396, 4, 0, 13, 36, 17, 214]

the 'day' was 0.

in the screenshot below it is shown that the original time is correct;

thanks : )

![image](https://user-images.githubusercontent.com/5755214/27253728-202e2228-538f-11e7-87f9-25481a56a1b9.png)

**Comment by babakhani** [comment]
Fixed on 0.2.0
