### ISSUE TITLE
Parse unix date doesn't work properly

### ISSUE THREAD

**Issue by bitaedalati** [babakhani/PersianDate#35]
this line of document doesnt work
var day = new persianDate.unix(1318781876);

**Comment by ho3ein-mola** [comment]
> this line of document doesnt work
> var day = new persianDate.unix(1318781876);

i have same problem , 

```js
var day = new persianDate.unix(1318781876);
console.log(day) 
 //output of console.log(day) is empty object
 >> value {}
```
