### ISSUE TITLE
بازه زمانی

### ISSUE THREAD

**Issue by heidarymr** [babakhani/PersianDate#36]
سلام
آیا راهی برای انتخاب بازه زمانی وجود دارد؟

**Comment by babakhani** [comment]
@heidarymr 
این سوال باید در اینجا مطرح شود
https://github.com/babakhani/pwt.datepicker/issues
همچنین امیدوارم لینک زیر کمکتون کنه
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#range-selector
