### ISSUE TITLE
مشکل با سی و یکمین روز ماه های میلادی

### ISSUE THREAD

**Issue by hamidhx** [babakhani/PersianDate#37]
سلام
من دیروز که 31 آگوست بود تقویم رو تست می کردم کلا به هم ریخته بود
داخل مثال های لینک http://babakhani.github.io/PersianWebToolkit/beta/datepicker/example/
هم تست می کردم همه اش به هم ریخته بود مثلا ماه مهر رو نشون نمیداد

برای تست و صحت این موضوع تاریخ ویندوز را روی 31 آگوست یا اکتبر تنظیم کنید متوجه عرایض بنده میشید
ممنون از پیگیریتون

**Comment by babakhani** [comment]
@hamidhx  thanks for taking your time and create the issue.

I found this, and I think this is so weird. 
https://stackoverflow.com/questions/25741647/new-date-set-to-31-december-2014-says-1st-december-instead

I fix this issue on `beta` branch, you install with 

`npm install persian-date@beta`

you can check it and if everything were ok, I can merge it with `master` branch

**Comment by hamidhx** [comment]
Thanks for changes...
With the quick test that I did, I think it's OK in beta 0.2.5

thanks again!
