### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by mkomeily** [babakhani/PersianDate#39]
Installing using with **Bower** with this syntax 
`bower install persian-date --save-dev`
but faced with this mesage at the end 
`bower cached        https://github.com/babakhani/PersianDate.git#1.0.1`
`bower validate      1.0.1 against https://github.com/babakhani/PersianDate.git#*`
`bower ENOTFOUND     Package persian-daete not found`

Exactly this word , _**persian-daete**_ ,Not a missspelling

**Comment by babakhani** [comment]
when did you try this? at this time everything is ok in `bower`. 
Also, you can see: [Link1](https://github.com/babakhani/PersianDate/search?utf8=%E2%9C%93&q=+persian-daete&type=) [Link2](https://github.com/babakhani/pwt.datepicker/search?utf8=%E2%9C%93&q=+persian-daete&type=)
