### ISSUE TITLE
مشکل در نمایش ساعت 12 بعد از ظهر

### ISSUE THREAD

**Issue by iPazooki** [babakhani/PersianDate#41]
با سلام
اگر ساعت نمایشی بصورت 12.15 بعد از ظهر باشد به این صورت با فرمت LT نمایش داده می شود : 00:15 ب.ظ
 که باید به این صورت باشد 12.15 ب.ظ
فقط در بازه زمانی صبح است که 00:15 دقیقه معنی دارد و برای 12 ظهر بعد بعد تا 13 باید خود عدد 12 نمایش داده شود و نه اینکه صفر شود.

**Comment by babakhani** [comment]
@iPazooki 
با اینکه خوندن این متن در هم سخت بود ولی به نظر متوجه منظورتون شدم
این مورد در نسخه
v1.0.3
برطرف شده است.
شاد باشید
