### ISSUE TITLE
مشکل با نسخه جدید

### ISSUE THREAD

**Issue by hesampour** [babakhani/PersianDate#45]
به نام خدا

سلام
 نمی دونم در به روزرسانی چه اتفاقی افتاده که persianDate شناخته نمیشه. مشکلی با نسخه های قدیمی ندارم ولی هر زمان که به روزرسانی می کنم به این مشکل بر موخورم. من از این بسته برای انگولار 2 استفاده می کنم و با دستور زیر import می کنم
import '../../../../../node_modules/persian-date/dist/persian-date';
declare var persianDate;
ولی هر زمان که به روز می کنم به مشکل persianDate is no defiend بر می خورم

**Comment by babakhani** [comment]
متاسفانه متن خوانا نیست
