### ISSUE TITLE
مشکل در نسخه های قدیمی فایرفاکس

### ISSUE THREAD

**Issue by AhmadValipour** [babakhani/PersianDate#46]
سلام
تو نسخه 64 بیتی 56.0.2 وقتی تاریخ 2 فروردین رو میدم معادل تاریخ میلادی 21 مارس رو بهم میده در صورتی که باید 22 مارس رو بهم بده
var t = new persianDate([1397,01,02]);
gDate => Date 2018-03-21T20:30:00.000Z

**Comment by babakhani** [comment]
I check this on Firefox 56.0.2 and everything works well. 
however, I did not access to windows 64-bit station. my test environment is on a 32bit window and Firefox 56.0.2 and also mac os firefox 56.0.2
