### ISSUE TITLE
مشکل در اضافه کردن ماه

### ISSUE THREAD

**Issue by amijafari** [babakhani/PersianDate#48]
وقتی به ماه آخر سال یک ماه اضافه می‌کنیم بجای ۲۹ روز ۳۰ روز بعد محاسبه می‌شه. مثلا وقتی تاریخ ۱/۱۲/۱۳۹۶ ایجاد بشه و با تابع add یک ماه اضافه بشه تاریخ ۲/۱/۱۳۹۷ تولید می‌شه.
(new persianDate([1396, 12, 1])).add('months', 1).format() --> 1397-01-02

**Comment by babakhani** [comment]
تعداد روز های ماه در هنگام افزودن ماه محاسبه نمی شود
اگر قرار ۲۹ روز به زمان شما اضافه بشه بهتره با افزودن روز  این کار و انجام بدین

**Comment by amijafari** [comment]
ممنون از پاسخ ولی خب مشکل برای مواقعیه که معلوم نیست چند روز قراره اضافه بشه. مثلا من یک حلقه دارم که قراره هربار تاریخ رو یک ماه جلو ببره و معلوم نیست چه ماهیه. عملا اینجوری غیرقابل استفاده‌س.
