### ISSUE TITLE
Diff method always returns a positive value

### ISSUE THREAD

**Issue by aminmsvi** [babakhani/PersianDate#49]
Hello.
Diff method always returns a positive value regardless of input values, but in [documentation](http://babakhani.github.io/PersianWebToolkit/beta/persian-date/#difference) you have said the result will be a negative value if `a` is less than `b`. I looked at the source code and found out in [this](https://github.com/babakhani/PersianDate/blob/be079310276528df8a119535408ea0377336238d/src/pDate.js#L686) line you are multiplying the output value by -1 if its negative.
Is it an intended behavior or a bug?

**Comment by babakhani** [comment]
@aminmsvi 
This is definitely not the right behavior thanks for the report.
bug confirm, will be fixed in next version.

**Comment by babakhani** [comment]
@aminmsvi
you can test the new RC version.
```npm install persian-date@next```
