### ISSUE TITLE
disable some dates

### ISSUE THREAD

**Issue by mhmsignin** [babakhani/PersianDate#50]
سلام باباخانی عزیز و ممنون بابت پلاگینی که وقت گذاشتی و توسعش دادی، ممنونتم و من دارم از این پلاگین تو یه پروژه mvc code first استفاده میکنم.
اگه بتونی امکان غیر فعال کردن روزها رو بهش اضافه کنی ، مثله اون چیزی که تو تقویم بوت استرپ هست دیگه عالی میشه، یعنی مثلا روزهایه جمعه و یا روزهایه تعطیل رسمی رو غیر فعال کنه کاربر به انتخاب خودش، اگه بشه که عالی و کامل میشه این پلاگین.
بازم ممنونتم بابت کاره خوبت

**Comment by babakhani** [comment]
Please follow date picker issues [here](https://github.com/babakhani/pwt.datepicker/issues)
Also, we have this ability in datepicker, read the docs.
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#checkdate
