### ISSUE TITLE
persian digit

### ISSUE THREAD

**Issue by bahmansh** [babakhani/PersianDate#57]
When i want to use datepicker value, it return persian digits, so my system can not recognize it.
![ashampoo_snap_ 5 1397_11h19m06s_001_](https://user-images.githubusercontent.com/19801131/48999958-656a6180-f16d-11e8-8f5b-ea5ed9158635.png)

**Comment by RGitHuben** [comment]
same problem ???

**Comment by hosseincode** [comment]
You need to use the toLocale('en') like this:

`new persianDate([1396,6,17]).toLocale('en').format(); // "1397-06-17 00:00:00 AM"
`

Check out the [toLocate ](https://github.com/babakhani/PersianDate#tolocale) section of the guide for more info.

**Comment by babakhani** [comment]
Also, you can use `altField` and `altFieldFormatter`
More in Document
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#altfield
