### ISSUE TITLE
تاریخ نشان داده شده وقتی اینپوت شامل زمان باشد

### ISSUE THREAD

**Issue by Siyavoshi** [babakhani/PersianDate#59]
وقت بخیر.
اگر ولیو اینپوت فقط تاریخ باشه، مثلا 1397/11/11، وقتی روی اینپوت کلیک شه ودیت پیکر نشون داده شده، تاریخ از قبل سلکت شده مقدار اینپوت میشه.
اما اگه زمان هم اضافه بشه، مثلا 1397/11/11 12:12:12، زمان سکلت شده وقتی دیت پیکر باز شه زمان امروز میشه.
راهی داره که بشه اینو تغییر داد؟

**Comment by babakhani** [comment]
Hi 
please follow datepicker issues [here](https://github.com/babakhani/pwt.datepicker/issues), thanks.
