### ISSUE TITLE
"toCalendar" not working

### ISSUE THREAD

**Issue by ttvd94** [babakhani/PersianDate#60]
Using version 1.0.5, `toCalendar` not working correctly. I need to convert _Gregorian_ to _Persian_ date but the same _Gregorian_ date is returned.

```
var date = new persianDate([2018]).toCalendar('persian').format('YYYY');
// Output is ۲۰۱۸
```

**Comment by babakhani** [comment]
this statement `var date = new persianDate([2018])` return Persian date. you convert it to Persian calendar again and the result is the same

**Comment by ttvd94** [comment]
Apparently result is not the same, but even wrong. Since the Persian match for Gregorian-2018 would be like 1397, so the expected output is ۱۳۹۷
