### ISSUE TITLE
A bug in subtract month

### ISSUE THREAD

**Issue by amindelavar** [babakhani/PersianDate#69]
for example if current date is 1398.1.1 and subtract month by 1 :
`let prev_month=new persianDate([1398, 1]).subtract('M', 1);`
prev_month : **1397.11** !!!

**Comment by babakhani** [comment]
We have some issues in add/subtract month and year, we currently work on it and this issue will be fixed in the next version. thank you for your time.

**Comment by fibodesign** [comment]
thanks for useful lib
yes subtract problem is TABLO! :)

**Comment by babakhani** [comment]
@amindelavar 
@tarnamaco 
you can test new RC version
```npm install persian-date@next```

**Comment by amindelavar** [comment]
> @amindelavar
> @tarnamaco
> you can test new RC version
> `npm install persian-date@next`
