### ISSUE TITLE
StartOf Week 

### ISSUE THREAD

**Issue by AminTaghikhani** [babakhani/PersianDate#71]
Hi,
At first, I wanted to thank you for this awesome library!

I'm writing to tell you that I've found a bug in this library.
I use `startOf('week')` to get the start of this week, but there is a bug in this function.
when the month changes, `startOf('week')` returns `startOf('day')` data.

For example, today is
Sunday Ordibehesht 1st
and the start of this week is
Saturday Farvardin 31st.
But `startOf('week')` returns
Sunday Ordibehest 1st,
not Saturday Farvardin 31st.

my library version: `v1.0.5`

**Comment by babakhani** [comment]
@AminTaghikhani 
you can test the new RC version.
`npm install persian-date@next`

**Comment by AminTaghikhani** [comment]
@babakhani 

Thanks, fixed. 

When is this version release?
