### ISSUE TITLE
استفاده در انگولار ۷

### ISSUE THREAD

**Issue by MansoorJafari** [babakhani/PersianDate#77]
سلام چطور میشه از این کتابخونه توی انگولار ۷ استفاده کرد
ممنون میشم راهنمایی کنید.

**Comment by mort3za** [comment]
Just import and use it like other npm packages. persianDate is pure javascript and can be used anywhere. 

```
import persianDate from "persian-date";
console.log( new persianDate([1398, 3, 10]).add('day', 1).toArray() )
```
