### ISSUE TITLE
convert date to utc

### ISSUE THREAD

**Issue by mojtabamn22** [babakhani/PersianDate#78]
i need convert jalali date to utc. 
how to convert?

**Comment by mort3za** [comment]
@mojtabamn22 example: `new persianDate([1396]).toCalendar('gregorian').toDate()`

**Comment by mojtabamn22** [comment]
> 
> 
> @mojtabamn22 example: `new persianDate([1396]).toCalendar('gregorian').toDate()`
> This returns a javascript native date object

tnx! but i want convert persian date to unix timestamp and again convert unix timestamo to persian date!
mycode like this
`var selectedTime = Date.UTC(1398, 03,18);
  var selectedDate = new Date(selectedTime);`

**Comment by mort3za** [comment]
`new persianDate([1398,3,18]).valueOf()` returns timestamp.  
`new persianDate(1559935800000).toArray()` to get persian date in array.

**Comment by mojtabamn22** [comment]
@mort3za 
tnx. with static number work. but not working with my code
i use jquery ui datepicker (persian) when i click date in datepicker how incorrect timestamp and date
see this image https://ibb.co/4ff6bzY
and this is mycode:
$('#datepicker7').datepicker({
                numberOfMonths: 3,
                onSelect: function (dateText, inst) {
                    
                    var selectedTime = new persianDate([inst.currentYear, inst.currentMonth+1, inst.currentDay]).valueOf();
                    
                    var selectedDate = new persianDate(selectedTime).toArray();
                    
                    console.log(selectedTime);
                    
                    console.log(selectedDate);
                }
            });
