### ISSUE TITLE
datepicker opens right of input

### ISSUE THREAD

**Issue by AmirZandi13** [babakhani/PersianDate#79]
how can i open modal of datepicker right of input?

**Comment by mort3za** [comment]
Here is PersianDate package github repository, not [datepicker](https://github.com/babakhani/pwt.datepicker)

Anyway, did you checked [position option](https://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#Config.position)?

**Comment by AmirZandi13** [comment]
thanks
