### ISSUE TITLE
Uncaught ReferenceError : persianDate is not defined

### ISSUE THREAD

**Issue by sajadabs** [babakhani/PersianDate#86]
Hi thank you for your efforts. 
I have a problem with adding using webpack, After installing the package and adding it to the project I get a message in console "Uncaught ReferenceError : persianDate is not defined".
What solution do you suggest?
Thanks!

**Comment by mort3za** [comment]
Probably you want to add it to global (window). If you import it everywhere you need it there should be no problem.  
Look at this gist for adding something to global in webpack:
https://gist.github.com/mort3za/2faf29064fd99784581a9a1497e90737

**Comment by ahmad-amani** [comment]
same there..

**Comment by mort3za** [comment]
@ahmad-amani did you try the solution above? what's the problem with it?
you need to add persianDate as a global variable similar to jQuery.

**Comment by sajadabs** [comment]
`window.persianDate = require('persian-date');`

thanks.
