### ISSUE TITLE
پیشنهاد توسعه

### ISSUE THREAD

**Issue by mehrdadashtari** [babakhani/PersianDate#99]
<div dir="rtl" lang="fa">سلام پیشنهادی دارم برای افزودن قابلیت نمایش مناسبت به برنامه ای که توسعه دادید

الان که همه ی سیستم ها به اینترنت متصل هستند پیشنهاد میکنم ارتباط با ای پی آي های تقویم رو هم در این سورس خوب پیاده سازی کنید
خودم از این سرویس زیاد استفاده میکنم </div>
<a href="https://apieco.ir/api/farsicalendar">وب سرویس تقویم فارسی</a>

<div dir="rtl" lang="fa">اطلاعات خوبی ارائه میده مثل وقایع و مناسبت های هر روز و دریافت رویداد در حالت شمسی و قمری و میلادی</div>

**Comment by mort3za** [comment]
Sorry, we can not add a web service dependency to this plugin.
